services:
    sonata.admin.category:
        class: Polcode\ProductBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - Polcode\ProductBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [PolcodeProductBundle]]
            
    sonata.admin.product:
        class: Polcode\ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Product" }
        arguments:
            - ~
            - Polcode\ProductBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [PolcodeProductBundle]]
        sonata.admin.user:
          class: Application\Sonata\UserBundle\Admin\TestAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: users, label: users, label_translator_strategy: sonata.admin.label.strategy.underscore }
          arguments:
              - null
              - Application\Sonata\UserBundle\Entity\User
              - SonataAdminBundle:CRUD
          calls:
              - [setTranslationDomain, [SonataUserBundle]]
              - [setUserManager, [@fos_user.user_manager]]
              - [setSecurityContext, [@security.context]]