services:
    sonata.admin.category:
        class: Polcode\ProductBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - Polcode\ProductBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [PolcodeProductBundle]]
    sonata.admin.product:
        class: Polcode\ProductBundle\Admin\ProductAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Product" }
        arguments:
            - ~
            - Polcode\ProductBundle\Entity\Product
            - ~
        calls:
            - [ setTranslationDomain, [PolcodeProductBundle]]