services:
    sonata.admin.post:
        class: Polcode\ProductBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Category" }
        arguments:
            - ~
            - Polcode\ProductBundle\Entity\Category
            - ~
        calls:
            - [ setTranslationDomain, [PolcodeProductBundle]]